spring.application.name=clothing-shop
spring.jooq.sql-dialect=POSTGRES
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
